default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USER") { "panorama" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "panorama" } %>
  database: panorama_development

test:
  <<: *default
  database: panorama_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
